msm: kgsl: revert few changes to fix gpu iommu fault
Fixes:
[   20.530036] kgsl kgsl-3d0: CP initialization failed to idle
[   20.530053] kgsl kgsl-3d0: rb=0 pos=F/F rbbm_status=00000001/00000000 int_0_status=00000000
[   20.530058] kgsl kgsl-3d0:  hwfault=00000000
[   20.539120] kgsl kgsl-3d0: |kgsl_iommu_fault_handler| GPU PAGE FAULT: addr = FCAFC000 pid= 0
[   20.539160] kgsl kgsl-3d0: |kgsl_iommu_fault_handler| context=gfx3d_user ctx_type=UNKNOWN TTBR0=0x40001c3496000 CIDR=0x0 (write permission fault)
[   20.539188] kgsl kgsl-3d0: |kgsl_iommu_fault_handler| FAULTING BLOCK: CP
[   20.542578] CPU4: update max cpu_capacity 764
[   20.643014] logd: logdr: UID=1000 GID=1003 PID=2715 n tail=500 logMask=8 pid=2537 start=0ns deadline=0ns
[   20.644083] logd: logdr: UID=1000 GID=1003 PID=2715 n tail=500 logMask=1 pid=2537 start=0ns deadline=0ns

Revert "msm: kgsl: Mark the scratch buffer as privileged"

This reverts commit 76518d99f872d988bb7b789486094219782b0921.

Revert "msm: kgsl: Keep postamble packets in a privileged buffer"

This reverts commit 62ab4b820ff8765807b415c08ecb100aebcc85cd.

drivers: gpu: switch to counters

../drivers/gpu/msm/adreno_a6xx_preempt.c:564:4: error: no member named 'scratch' in 'struct adreno_preemption'
  564 |                         PREEMPT_SCRATCH_ADDR(adreno_dev, KMD_POSTAMBLE_IDX);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/gpu/msm/adreno.h:259:18: note: expanded from macro 'PREEMPT_SCRATCH_ADDR'
  259 |         ((dev)->preempt.scratch.gpuaddr + (id * sizeof(u64)))
      |          ~~~~~~~~~~~~~~ ^
../drivers/gpu/msm/adreno_a6xx_preempt.c:803:29: error: no member named 'scratch' in 'struct adreno_preemption'
  803 |                 u32 *postamble = preempt->scratch.hostptr +
      |                                  ~~~~~~~  ^
2 errors generated.

Signed-off-by: duckyduckg <duckyduckg65@gmail.com>